// This file is auto-generated by @hey-api/openapi-ts

export type Body_AccountUpdateMe = {
    username?: string | null;
    email?: string | null;
    name?: string | null;
    description?: string | null;
    thumbnail?: (Blob | File) | null;
};

export type Body_PublicLogin = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CommentAuthor = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type CommentDisplayResponse = {
    id: number;
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
    author: CommentAuthor;
    deleted: boolean;
    created: string;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    children: Array<CommentDisplayResponse>;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type CommentResourceCreateRequest = {
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
};

export type CommentResourceResponse = {
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
    id: number;
    author: CommentAuthor;
    deleted: boolean;
    created: string;
};

export type CommentUpdateRequest = {
    parent_id?: number | null;
    thread_id?: number;
    content?: string;
    is_question?: boolean;
    solved?: boolean;
    pinned?: boolean;
    deleted?: boolean | null;
};

export type ExamAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    weight: number;
};

export type ExamAssessReadyRequest = {
    verification_code?: string;
};

export type ExamAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    cutoff_percent: number;
    submission: ExamAssessSubmission | null;
    kind: LearningResourceKind;
    owner: ExamOwner;
    finding: {
    [key: string]: ExamQuestionFinding;
} | null;
    final_message: string;
    verification_required: boolean;
    duration: number;
    exam_kind: ExamKind;
    score: number | null;
    status: SubmissionStatus | null;
};

export type ExamAssessStartRequest = {
    start_time: string;
};

export type ExamAssessSubmission = {
    verification_code: string;
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
    earned_score: number;
    possible_score: number;
    graded_time: string | null;
    questions: Array<ExamAsseccQuestion>;
};

export type ExamAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type ExamDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: ExamOwner;
    modified: string;
    submission_count: number;
    passed_count: number;
    question_count: number;
    exam_kind: ExamKind;
    duration: number;
    cutoff_percent: number;
    verification_required: boolean;
    question_composition: {
        [key: string]: (number);
    };
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    score: number | null;
    status: SubmissionStatus | null;
};

export type ExamGradingExam = {
    id: string;
    title: string;
    exam_kind: ExamKind;
};

export type ExamGradingRequest = {
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
};

export type ExamGradingSubmissionReponse = {
    id: string;
    user: ExamSubmissionUser;
    score: number | null;
    status: SubmissionStatus | null;
    end_time: string | null;
    graded_time: string | null;
    exam: ExamGradingExam;
};

export type ExamKind = 'midterm_exam' | 'final_exam' | 'assignment' | 'general_exam';

export type ExamOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ExamQuestionFinding = {
    kind: ExamQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    correct_answer: string;
    weight: number;
    explanation: string;
    answer_criteria: string;
    grading_method: string;
    reference: string;
    keywords: string;
};

export type ExamQuestionKind = 'single_selection' | 'ox_selection' | 'text_input' | 'number_input' | 'essay';

export type ExamResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    exam_kind: ExamKind;
    duration: number;
    question_composition: ExamResourceQuestionComposition;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    verification_required: boolean;
    questions: Array<ExamResourceQuestionCreate>;
};

export type ExamResourceQuestionComposition = {
    single_selection?: number;
    ox_selection?: number;
    text_input?: number;
    number_input?: number;
    essay?: number;
};

export type ExamResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    answer_criteria: string;
    explanation: string;
    reference: string;
    keywords: string;
    weight: number;
};

export type ExamResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    answer_criteria: string;
    explanation: string;
    reference: string;
    keywords: string;
    weight: number;
    id: number;
};

export type ExamResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: ExamQuestionKind;
    selections?: Array<(string)>;
    correct_answer?: string;
    answer_criteria?: string;
    explanation?: string;
    reference?: string;
    keywords?: string;
    weight?: number;
    id?: number | null;
};

export type ExamResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    exam_kind: ExamKind;
    duration: number;
    question_composition: ExamResourceQuestionComposition;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    verification_required: boolean;
    questions: Array<ExamResourceQuestionResource>;
    id: string;
    owner: ExamOwner;
    modified: string;
};

export type ExamResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    success_message?: string;
    failure_message?: string;
    exam_kind?: ExamKind;
    duration?: number;
    question_composition?: ExamResourceQuestionComposition;
    cutoff_percent?: number;
    randomize?: boolean;
    enable_finding?: boolean;
    verification_required?: boolean;
    questions?: Array<ExamResourceQuestionUpdate>;
};

export type ExamSubmissionResponse = {
    user: ExamSubmissionUser;
    start_time: string | null;
    end_time: string | null;
    score: number | null;
    status: string | null;
};

export type ExamSubmissionUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LearningResourceKind = 'video' | 'short' | 'quiz' | 'survey' | 'exam' | 'course' | 'group' | 'post';

export type Paginated_CommentDisplayResponse_ = {
    items: Array<CommentDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamDisplayResponse_ = {
    items: Array<ExamDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamGradingSubmissionReponse_ = {
    items: Array<ExamGradingSubmissionReponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamSubmissionResponse_ = {
    items: Array<ExamSubmissionResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_QuizDisplayResponse_ = {
    items: Array<QuizDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_QuizSubmissionResponse_ = {
    items: Array<QuizSubmissionResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_SurveyDisplayResponse_ = {
    items: Array<SurveyDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_SurveySubmissionResponse_ = {
    items: Array<SurveySubmissionResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ThreadResponse_ = {
    items: Array<ThreadResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type PasswordResetConfirmRequest = {
    token: string;
    new_password: string;
};

export type PasswordResetRequest = {
    email: string;
    confirm_url: string;
};

export type QuizAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    weight: number;
};

export type QuizAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    cutoff_percent: number;
    submission: QuizAssessSubmission | null;
    kind: LearningResourceKind;
    owner: QuizOwner;
    finding: {
    [key: string]: QuizQuestionFinding;
} | null;
    final_message: string;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizAssessSubmission = {
    verification_code: string;
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
    earned_score: number;
    possible_score: number;
    questions: Array<QuizAsseccQuestion>;
};

export type QuizAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type QuizDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: QuizOwner;
    modified: string;
    submission_count: number;
    passed_count: number;
    question_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type QuizQuestionFinding = {
    kind: QuizQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    correct_answer: string;
    weight: number;
};

export type QuizQuestionKind = 'single_selection' | 'number_input';

export type QuizResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<QuizResourceQuestionCreate>;
};

export type QuizResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    weight: number;
};

export type QuizResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    weight: number;
    id: number;
};

export type QuizResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: QuizQuestionKind;
    selections?: Array<(string)>;
    correct_answer?: string;
    weight?: number;
    id?: number | null;
};

export type QuizResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<QuizResourceQuestionResource>;
    id: string;
    owner: QuizOwner;
    modified: string;
};

export type QuizResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    success_message?: string;
    failure_message?: string;
    cutoff_percent?: number;
    randomize?: boolean;
    enable_finding?: boolean;
    questions?: Array<QuizResourceQuestionUpdate>;
};

export type QuizSubmissionResponse = {
    user: QuizSubmissionUser;
    start_time: string | null;
    end_time: string | null;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizSubmissionUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ResendVerificationEmailRequest = {
    email: string;
    email_verification_url: string;
};

export type SubmissionStatus = 'passed' | 'failed' | 'grading' | 'timeout' | 'in_progress' | 'ready';

export type SurveyAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
};

export type SurveyAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    submission: SurveyAssessSubmission | null;
    kind: LearningResourceKind;
    owner: SurveyOwner;
    finding: {
    [key: string]: SurveyQuestionFinding;
} | null;
    final_message: string;
    status: SubmissionStatus | null;
    enable_finding: boolean;
    submission_count: number;
};

export type SurveyAssessSubmission = {
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    questions: Array<SurveyAsseccQuestion>;
};

export type SurveyAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type SurveyDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: SurveyOwner;
    modified: string;
    submission_count: number;
    question_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    status: SubmissionStatus | null;
};

export type SurveyOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type SurveyQuestionFinding = {
    kind: SurveyQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    mandatory: boolean | null;
};

export type SurveyQuestionKind = 'single_selection' | 'multiple_selection' | 'number_input' | 'text_input';

export type SurveyResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    complete_message: string;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<SurveyResourceQuestionCreate>;
};

export type SurveyResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
};

export type SurveyResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
    id: number;
};

export type SurveyResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: SurveyQuestionKind;
    selections?: Array<(string)>;
    mandatory?: boolean;
    id?: number | null;
};

export type SurveyResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    complete_message: string;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<SurveyResourceQuestionResource>;
    id: string;
    owner: SurveyOwner;
    modified: string;
};

export type SurveyResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    complete_message?: string;
    randomize?: boolean;
    enable_finding?: boolean;
    questions?: Array<SurveyResourceQuestionUpdate>;
};

export type SurveySubmissionResponse = {
    user: SurveySubmissionUser;
    end_time: string | null;
    status: SubmissionStatus | null;
};

export type SurveySubmissionUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ThreadCreateRequest = {
    owner_id: number;
    thumbnail?: string;
    title: string;
    url: string;
    kind: LearningResourceKind;
};

export type ThreadOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ThreadResponse = {
    id: number;
    thumbnail: string;
    title: string;
    owner: ThreadOwner;
    url: string;
    kind: LearningResourceKind;
    comment_count: number;
    question_count: number;
    unsolved_count: number;
    created: string;
};

export type UserCreateRequest = {
    username: string;
    email: string;
    password: string;
    name: string;
    email_verification_url: string;
};

export type UserResponse = {
    id: number;
    username: string;
    email: string;
    name: string;
    thumbnail: string;
    description: string;
    created: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PublicCreateUserData = {
    requestBody: UserCreateRequest;
};

export type PublicCreateUserResponse = unknown;

export type PublicVerifyEmailData = {
    token: string;
};

export type PublicVerifyEmailResponse = unknown;

export type PublicResendVerificationEmailData = {
    requestBody: ResendVerificationEmailRequest;
};

export type PublicResendVerificationEmailResponse = unknown;

export type PublicLoginData = {
    formData: Body_PublicLogin;
};

export type PublicLoginResponse = unknown;

export type AccountLogoutData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type AccountLogoutResponse = unknown;

export type PublicPasswordResetData = {
    requestBody: PasswordResetRequest;
};

export type PublicPasswordResetResponse = unknown;

export type PublicPasswordResetConfirmData = {
    requestBody: PasswordResetConfirmRequest;
};

export type PublicPasswordResetConfirmResponse = unknown;

export type AccountGetMeData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type AccountGetMeResponse = UserResponse;

export type AccountUpdateMeData = {
    accessToken?: string | null;
    formData?: Body_AccountUpdateMe;
    refreshToken?: string | null;
};

export type AccountUpdateMeResponse = UserResponse;

export type AccountGetUserData = {
    accessToken?: string | null;
    id: number;
    refreshToken?: string | null;
};

export type AccountGetUserResponse = UserResponse;

export type AccountGetUserByUsernameData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    username: string;
};

export type AccountGetUserByUsernameResponse = UserResponse;

export type CommentGetThreadData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    url: string;
};

export type CommentGetThreadResponse = ThreadResponse;

export type CommentGetThreadsData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'comment_count' | 'question_count' | 'unsolved_count';
    ownerId?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type CommentGetThreadsResponse = Paginated_ThreadResponse_;

export type CommentCreateThreadData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ThreadCreateRequest;
};

export type CommentCreateThreadResponse = ThreadResponse;

export type CommentGetDisplayData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'like_count';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    threadId?: number | null;
};

export type CommentGetDisplayResponse = Paginated_CommentDisplayResponse_;

export type CommentCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: CommentResourceCreateRequest;
};

export type CommentCreateResourceResponse = CommentResourceResponse;

export type CommentUpdateResourceData = {
    accessToken?: string | null;
    id: number;
    refreshToken?: string | null;
    requestBody: CommentUpdateRequest;
};

export type CommentUpdateResourceResponse = CommentResourceResponse;

export type CommentToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: number;
    refreshToken?: string | null;
};

export type CommentToggleActionResponse = unknown;

export type QuizGetDisplayData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    submitter?: number | null;
};

export type QuizGetDisplayResponse = Paginated_QuizDisplayResponse_;

export type QuizGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizGetResourceResponse = QuizResourceResponse;

export type QuizUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: QuizResourceUpdateRequest;
};

export type QuizUpdateResourceResponse = QuizResourceResponse;

export type QuizDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizDeleteResourceResponse = unknown;

export type QuizCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: QuizResourceCreateRequest;
};

export type QuizCreateResourceResponse = QuizResourceResponse;

export type QuizGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizGetAssessResponse = QuizAssessResponse;

export type QuizReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizReadyAssessResponse = QuizAssessResponse;

export type QuizSubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: QuizAssessSubmitRequest;
};

export type QuizSubmitAssessResponse = QuizAssessResponse;

export type QuizDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizDeleteAssessResponse = unknown;

export type QuizGetQuizSubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type QuizGetQuizSubmissionsResponse = Paginated_QuizSubmissionResponse_;

export type QuizDownloadQuizSubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type QuizDownloadQuizSubmissionsResponse = string;

export type QuizToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type QuizToggleActionResponse = unknown;

export type QuizGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type QuizGetOwnedQuestionsResponse = Array<QuizResourceQuestionResource>;

export type SurveyGetDisplayData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    submitter?: number | null;
};

export type SurveyGetDisplayResponse = Paginated_SurveyDisplayResponse_;

export type SurveyGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyGetResourceResponse = SurveyResourceResponse;

export type SurveyUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: SurveyResourceUpdateRequest;
};

export type SurveyUpdateResourceResponse = SurveyResourceResponse;

export type SurveyDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyDeleteResourceResponse = unknown;

export type SurveyCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: SurveyResourceCreateRequest;
};

export type SurveyCreateResourceResponse = SurveyResourceResponse;

export type SurveyGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyGetAssessResponse = SurveyAssessResponse;

export type SurveyReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyReadyAssessResponse = SurveyAssessResponse;

export type SurveySubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: SurveyAssessSubmitRequest;
};

export type SurveySubmitAssessResponse = SurveyAssessResponse;

export type SurveyDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyDeleteAssessResponse = unknown;

export type SurveyGetSurveySubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type SurveyGetSurveySubmissionsResponse = Paginated_SurveySubmissionResponse_;

export type SurveyDownloadSurveySubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type SurveyDownloadSurveySubmissionsResponse = string;

export type SurveyToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type SurveyToggleActionResponse = unknown;

export type SurveyGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type SurveyGetOwnedQuestionsResponse = Array<SurveyResourceQuestionResource>;

export type ExamGetDisplayData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    submitter?: number | null;
};

export type ExamGetDisplayResponse = Paginated_ExamDisplayResponse_;

export type ExamGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamGetResourceResponse = ExamResourceResponse;

export type ExamUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamResourceUpdateRequest;
};

export type ExamUpdateResourceResponse = ExamResourceResponse;

export type ExamDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamDeleteResourceResponse = unknown;

export type ExamCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ExamResourceCreateRequest;
};

export type ExamCreateResourceResponse = ExamResourceResponse;

export type ExamGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamGetAssessResponse = ExamAssessResponse;

export type ExamReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessReadyRequest;
};

export type ExamReadyAssessResponse = ExamAssessResponse;

export type ExamStartAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessStartRequest;
};

export type ExamStartAssessResponse = ExamAssessResponse;

export type ExamSubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessSubmitRequest;
};

export type ExamSubmitAssessResponse = ExamAssessResponse;

export type ExamDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamDeleteAssessResponse = unknown;

export type ExamGetGradingData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    userId: number;
};

export type ExamGetGradingResponse = ExamAssessResponse;

export type ExamSubmitGradingData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamGradingRequest;
    userId: number;
};

export type ExamSubmitGradingResponse = ExamAssessResponse;

export type ExamGetExamSubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time' | 'start_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type ExamGetExamSubmissionsResponse = Paginated_ExamSubmissionResponse_;

export type ExamDownloadExamSubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time' | 'start_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type ExamDownloadExamSubmissionsResponse = string;

export type ExamToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type ExamToggleActionResponse = unknown;

export type ExamGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type ExamGetOwnedQuestionsResponse = Array<ExamResourceQuestionResource>;

export type ExamGetGradingSubmissionsData = {
    accessToken?: string | null;
    asOf?: string | null;
    orderBy?: 'end_time' | 'start_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type ExamGetGradingSubmissionsResponse = Paginated_ExamGradingSubmissionReponse_;

export type $OpenApiTs = {
    '/api/v2/account/user': {
        post: {
            req: PublicCreateUserData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/user/verifyemail': {
        get: {
            req: PublicVerifyEmailData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PublicResendVerificationEmailData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/login': {
        post: {
            req: PublicLoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: AccountLogoutData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/password/reset': {
        post: {
            req: PublicPasswordResetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PublicPasswordResetConfirmData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/user/me': {
        get: {
            req: AccountGetMeData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: AccountUpdateMeData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/user/{id}': {
        get: {
            req: AccountGetUserData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/account/user/{username}/': {
        get: {
            req: AccountGetUserByUsernameData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/thread/{url}': {
        get: {
            req: CommentGetThreadData;
            res: {
                /**
                 * Successful Response
                 */
                200: ThreadResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/thread': {
        get: {
            req: CommentGetThreadsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_ThreadResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CommentCreateThreadData;
            res: {
                /**
                 * Successful Response
                 */
                200: ThreadResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/comment/display': {
        get: {
            req: CommentGetDisplayData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_CommentDisplayResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/comment': {
        post: {
            req: CommentCreateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: CommentResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/comment/{id}': {
        patch: {
            req: CommentUpdateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: CommentResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/comment/comment/{id}/{action}': {
        patch: {
            req: CommentToggleActionData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/display': {
        get: {
            req: QuizGetDisplayData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_QuizDisplayResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/{id}': {
        get: {
            req: QuizGetResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: QuizUpdateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: QuizDeleteResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz': {
        post: {
            req: QuizCreateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/{id}/assess': {
        get: {
            req: QuizGetAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: QuizReadyAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: QuizSubmitAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: QuizAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: QuizDeleteAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/{id}/submission': {
        get: {
            req: QuizGetQuizSubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_QuizSubmissionResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/{id}/submission/download': {
        get: {
            req: QuizDownloadQuizSubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/quiz/{id}/{action}': {
        patch: {
            req: QuizToggleActionData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/quiz/question/': {
        get: {
            req: QuizGetOwnedQuestionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<QuizResourceQuestionResource>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/display': {
        get: {
            req: SurveyGetDisplayData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_SurveyDisplayResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/{id}': {
        get: {
            req: SurveyGetResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: SurveyUpdateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: SurveyDeleteResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey': {
        post: {
            req: SurveyCreateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/{id}/assess': {
        get: {
            req: SurveyGetAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: SurveyReadyAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: SurveySubmitAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: SurveyAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: SurveyDeleteAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/{id}/submission': {
        get: {
            req: SurveyGetSurveySubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_SurveySubmissionResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/{id}/submission/download': {
        get: {
            req: SurveyDownloadSurveySubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/survey/{id}/{action}': {
        patch: {
            req: SurveyToggleActionData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/survey/question/': {
        get: {
            req: SurveyGetOwnedQuestionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<SurveyResourceQuestionResource>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/display': {
        get: {
            req: ExamGetDisplayData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_ExamDisplayResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}': {
        get: {
            req: ExamGetResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: ExamUpdateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: ExamDeleteResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam': {
        post: {
            req: ExamCreateResourceData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamResourceResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}/assess': {
        get: {
            req: ExamGetAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: ExamReadyAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: ExamStartAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: ExamSubmitAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: ExamDeleteAssessData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}/grading/{user_id}': {
        get: {
            req: ExamGetGradingData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: ExamSubmitGradingData;
            res: {
                /**
                 * Successful Response
                 */
                200: ExamAssessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}/submission': {
        get: {
            req: ExamGetExamSubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_ExamSubmissionResponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}/submission/download': {
        get: {
            req: ExamDownloadExamSubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/exam/{id}/{action}': {
        patch: {
            req: ExamToggleActionData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/question/': {
        get: {
            req: ExamGetOwnedQuestionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ExamResourceQuestionResource>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v2/exam/submission': {
        get: {
            req: ExamGetGradingSubmissionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Paginated_ExamGradingSubmissionReponse_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};