// This file is auto-generated by @hey-api/openapi-ts

export type Body_AccountUpdateMe = {
    username?: string | null;
    email?: string | null;
    name?: string | null;
    description?: string | null;
    thumbnail?: (Blob | File) | null;
};

export type Body_ContentCreateResource = {
    title: string;
    is_public: boolean;
    featured: boolean;
    index_page: string;
    duration: number;
    passing_percent: number;
    thumbnail?: (Blob | File) | string | null;
};

export type Body_ContentUpdateResource = {
    title?: string;
    is_public?: boolean;
    featured?: boolean;
    index_page?: string;
    duration?: number;
    passing_percent?: number;
    thumbnail?: (Blob | File) | string | null;
};

export type Body_PlaylistCreateResource = {
    thumbnail?: (Blob | File) | string | null;
    title: string;
    description?: string;
    is_public: boolean;
    featured: boolean;
};

export type Body_PlaylistUpdateResource = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    thumbnail?: (Blob | File) | string | null;
};

export type Body_PublicLogin = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_VideoUpdateResource = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    passing_percent?: number;
    thumbnail?: (Blob | File) | string | null;
};

export type CommentAuthor = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type CommentDisplayResponse = {
    id: number;
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
    author: CommentAuthor;
    deleted: boolean;
    created: string;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    children: Array<CommentDisplayResponse>;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type CommentResourceCreateRequest = {
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
};

export type CommentResourceResponse = {
    parent_id?: number | null;
    thread_id: number;
    content: string;
    is_question: boolean;
    solved: boolean;
    pinned: boolean;
    id: number;
    author: CommentAuthor;
    deleted: boolean;
    created: string;
};

export type CommentUpdateRequest = {
    parent_id?: number | null;
    thread_id?: number;
    content?: string;
    is_question?: boolean;
    solved?: boolean;
    pinned?: boolean;
    deleted?: boolean | null;
};

export type ContentDisplayResponse = {
    id: string;
    title: string;
    is_public: boolean;
    featured: boolean;
    modified: string;
    duration: number;
    passing_percent: number;
    thumbnail: string;
    uploaded: boolean;
    owner: ContentOwner;
};

export type ContentOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ContentResourceResponse = {
    id: string;
    title: string;
    is_public: boolean;
    featured: boolean;
    duration: number;
    passing_percent: number;
    index_page: string;
    modified: string;
    uploaded: boolean;
    thumbnail: (Blob | File) | string;
    owner: ContentOwner;
};

export type ContentResourceUpdateRequest = {
    title?: string | null;
    is_public?: boolean | null;
    featured?: boolean | null;
    index_page?: string | null;
    duration?: number | null;
    passing_percent?: number | null;
    uploaded?: boolean | null;
};

export type ContentViewResponse = {
    id: string;
    title: string;
    is_public: boolean;
    featured: boolean;
    modified: string;
    duration: number;
    passing_percent: number;
    thumbnail: string;
    uploaded: boolean;
    owner: ContentOwner;
};

export type ExamAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    weight: number;
};

export type ExamAssessReadyRequest = {
    verification_code?: string;
};

export type ExamAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    cutoff_percent: number;
    submission: ExamAssessSubmission | null;
    kind: LearningResourceKind;
    owner: ExamOwner;
    finding: {
    [key: string]: ExamQuestionFinding;
} | null;
    final_message: string;
    verification_required: boolean;
    duration: number;
    exam_kind: ExamKind;
    score: number | null;
    status: SubmissionStatus | null;
};

export type ExamAssessStartRequest = {
    start_time: string;
};

export type ExamAssessSubmission = {
    verification_code: string;
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
    earned_score: number;
    possible_score: number;
    graded_time: string | null;
    questions: Array<ExamAsseccQuestion>;
};

export type ExamAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type ExamDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: ExamOwner;
    modified: string;
    submission_count: number;
    passed_count: number;
    question_count: number;
    exam_kind: ExamKind;
    duration: number;
    cutoff_percent: number;
    verification_required: boolean;
    question_composition: {
        [key: string]: (number);
    };
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    score: number | null;
    status: SubmissionStatus | null;
};

export type ExamGradingExam = {
    id: string;
    title: string;
    exam_kind: ExamKind;
};

export type ExamGradingRequest = {
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
};

export type ExamGradingSubmissionReponse = {
    id: string;
    user: ExamSubmissionUser;
    score: number | null;
    status: SubmissionStatus | null;
    end_time: string | null;
    graded_time: string | null;
    exam: ExamGradingExam;
};

export type ExamKind = 'midterm_exam' | 'final_exam' | 'assignment' | 'general_exam';

export type ExamOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ExamQuestionFinding = {
    kind: ExamQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    correct_answer: string;
    weight: number;
    explanation: string;
    answer_criteria: string;
    grading_method: string;
    reference: string;
    keywords: string;
};

export type ExamQuestionKind = 'single_selection' | 'ox_selection' | 'text_input' | 'number_input' | 'essay';

export type ExamReportResponse = {
    user: ExamSubmissionUser;
    start_time: string | null;
    end_time: string | null;
    score: number | null;
    status: string | null;
};

export type ExamResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    exam_kind: ExamKind;
    duration: number;
    question_composition: ExamResourceQuestionComposition;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    verification_required: boolean;
    questions: Array<ExamResourceQuestionCreate>;
};

export type ExamResourceQuestionComposition = {
    single_selection?: number;
    ox_selection?: number;
    text_input?: number;
    number_input?: number;
    essay?: number;
};

export type ExamResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    answer_criteria: string;
    explanation: string;
    reference: string;
    keywords: string;
    weight: number;
};

export type ExamResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: ExamQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    answer_criteria: string;
    explanation: string;
    reference: string;
    keywords: string;
    weight: number;
    id: number;
};

export type ExamResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: ExamQuestionKind;
    selections?: Array<(string)>;
    correct_answer?: string;
    answer_criteria?: string;
    explanation?: string;
    reference?: string;
    keywords?: string;
    weight?: number;
    id?: number | null;
};

export type ExamResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    exam_kind: ExamKind;
    duration: number;
    question_composition: ExamResourceQuestionComposition;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    verification_required: boolean;
    questions: Array<ExamResourceQuestionResource>;
    id: string;
    owner: ExamOwner;
    modified: string;
};

export type ExamResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    success_message?: string;
    failure_message?: string;
    exam_kind?: ExamKind;
    duration?: number;
    question_composition?: ExamResourceQuestionComposition;
    cutoff_percent?: number;
    randomize?: boolean;
    enable_finding?: boolean;
    verification_required?: boolean;
    questions?: Array<ExamResourceQuestionUpdate>;
};

export type ExamSubmissionUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImportYoutubeRequest = {
    youtube_id: string;
};

export type LearningResourceKind = 'video' | 'short' | 'quiz' | 'survey' | 'exam' | 'lesson' | 'course' | 'group' | 'post' | 'content';

export type LessonDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: LessonOwner;
    resources: Array<LessonResource>;
    progress: number | null;
    passed: boolean | null;
    modified: string;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type LessonOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type LessonResource = {
    kind: 'video' | 'quiz' | 'survey' | 'exam' | 'content';
    id: string;
    title: string;
};

export type kind = 'video' | 'quiz' | 'survey' | 'exam' | 'content';

export type LessonResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    resources: Array<LessonResource>;
};

export type LessonResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    resources: Array<LessonResource>;
    id: string;
    owner: LessonOwner;
};

export type LessonResourceSelectorResponse = {
    kind: 'quiz' | 'survey' | 'video' | 'exam' | 'content';
    id: string;
    title: string;
};

export type LessonResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    resources?: Array<LessonResource>;
};

export type LessonViewResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: LessonOwner;
    resources: Array<LessonResource>;
    progress: number | null;
    passed: boolean | null;
    modified: string;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type Paginated_CommentDisplayResponse_ = {
    items: Array<CommentDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ContentDisplayResponse_ = {
    items: Array<ContentDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamDisplayResponse_ = {
    items: Array<ExamDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamGradingSubmissionReponse_ = {
    items: Array<ExamGradingSubmissionReponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ExamReportResponse_ = {
    items: Array<ExamReportResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_LessonDisplayResponse_ = {
    items: Array<LessonDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_PlaylistDisplayResponse_ = {
    items: Array<PlaylistDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_QuizDisplayResponse_ = {
    items: Array<QuizDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_QuizReportResponse_ = {
    items: Array<QuizReportResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_SurveyDisplayResponse_ = {
    items: Array<SurveyDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_SurveyReportResponse_ = {
    items: Array<SurveyReportResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_ThreadResponse_ = {
    items: Array<ThreadResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_VideoDisplayResponse_ = {
    items: Array<VideoDisplayResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Paginated_VideoReportResponse_ = {
    items: Array<VideoReportResponse>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type PasswordResetConfirmRequest = {
    token: string;
    new_password: string;
};

export type PasswordResetRequest = {
    email: string;
    confirm_url: string;
};

export type PlaylistDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: PlaylistOwner;
    thumbnail: string;
    uploader: string;
    duration: number;
    video_count: number;
    progress: number | null;
    passed: boolean | null;
    passed_str: string | null;
    modified: string;
    live_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type PlaylistOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type PlaylistResourceResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: PlaylistOwner;
    uploader: string;
    thumbnail: (Blob | File) | string;
};

export type PlaylistResumeResponse = {
    video_id: string;
};

export type PlaylistVideoItem = {
    playlist_id: string;
    video_id: string;
    order: number | null;
};

export type PlaylistVideoRequest = {
    videos: Array<PlaylistVideoItem>;
};

export type PlaylistViewResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: PlaylistOwner;
    thumbnail: string;
    uploader: string;
    duration: number;
    video_count: number;
    progress: number | null;
    passed: boolean | null;
    passed_str: string | null;
    modified: string;
    live_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type QuizAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    weight: number;
};

export type QuizAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    cutoff_percent: number;
    submission: QuizAssessSubmission | null;
    kind: LearningResourceKind;
    owner: QuizOwner;
    finding: {
    [key: string]: QuizQuestionFinding;
} | null;
    final_message: string;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizAssessSubmission = {
    verification_code: string;
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    grading: {
        [key: string]: (number | null);
    };
    feedback: {
        [key: string]: (string | null);
    };
    earned_score: number;
    possible_score: number;
    questions: Array<QuizAsseccQuestion>;
};

export type QuizAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type QuizDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: QuizOwner;
    modified: string;
    submission_count: number;
    passed_count: number;
    question_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type QuizQuestionFinding = {
    kind: QuizQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    correct_answer: string;
    weight: number;
};

export type QuizQuestionKind = 'single_selection' | 'number_input';

export type QuizReportResponse = {
    user: QuizReportUser;
    start_time: string | null;
    end_time: string | null;
    score: number | null;
    status: SubmissionStatus | null;
};

export type QuizReportUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type QuizResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<QuizResourceQuestionCreate>;
};

export type QuizResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    weight: number;
};

export type QuizResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: QuizQuestionKind;
    selections: Array<(string)>;
    correct_answer: string;
    weight: number;
    id: number;
};

export type QuizResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: QuizQuestionKind;
    selections?: Array<(string)>;
    correct_answer?: string;
    weight?: number;
    id?: number | null;
};

export type QuizResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    success_message: string;
    failure_message: string;
    cutoff_percent: number;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<QuizResourceQuestionResource>;
    id: string;
    owner: QuizOwner;
    modified: string;
};

export type QuizResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    success_message?: string;
    failure_message?: string;
    cutoff_percent?: number;
    randomize?: boolean;
    enable_finding?: boolean;
    questions?: Array<QuizResourceQuestionUpdate>;
};

export type ResendVerificationEmailRequest = {
    email: string;
    email_verification_url: string;
};

export type SubmissionStatus = 'passed' | 'failed' | 'grading' | 'timeout' | 'in_progress' | 'ready';

export type SurveyAsseccQuestion = {
    id: number;
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
};

export type SurveyAssessResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    submission: SurveyAssessSubmission | null;
    kind: LearningResourceKind;
    owner: SurveyOwner;
    finding: {
    [key: string]: SurveyQuestionFinding;
} | null;
    final_message: string;
    status: SubmissionStatus | null;
    enable_finding: boolean;
    submission_count: number;
};

export type SurveyAssessSubmission = {
    start_time: string | null;
    end_time: string | null;
    answers: {
        [key: string]: (string);
    };
    questions: Array<SurveyAsseccQuestion>;
};

export type SurveyAssessSubmitRequest = {
    answers: {
        [key: string]: (string);
    };
};

export type SurveyDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    owner: SurveyOwner;
    modified: string;
    submission_count: number;
    question_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
    status: SubmissionStatus | null;
};

export type SurveyOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type SurveyQuestionFinding = {
    kind: SurveyQuestionKind;
    question: string;
    selections: Array<(string)>;
    occurrences: Array<(number)>;
    mandatory: boolean | null;
};

export type SurveyQuestionKind = 'single_selection' | 'multiple_selection' | 'number_input' | 'text_input';

export type SurveyReportResponse = {
    user: SurveyReportUser;
    end_time: string | null;
    status: SubmissionStatus | null;
};

export type SurveyReportUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type SurveyResourceCreateRequest = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    complete_message: string;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<SurveyResourceQuestionCreate>;
};

export type SurveyResourceQuestionCreate = {
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
};

export type SurveyResourceQuestionResource = {
    question: string;
    help_text: string;
    kind: SurveyQuestionKind;
    selections: Array<(string)>;
    mandatory: boolean;
    id: number;
};

export type SurveyResourceQuestionUpdate = {
    question?: string;
    help_text?: string;
    kind?: SurveyQuestionKind;
    selections?: Array<(string)>;
    mandatory?: boolean;
    id?: number | null;
};

export type SurveyResourceResponse = {
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    start_date: string;
    end_date: string | null;
    complete_message: string;
    randomize: boolean;
    enable_finding: boolean;
    questions: Array<SurveyResourceQuestionResource>;
    id: string;
    owner: SurveyOwner;
    modified: string;
};

export type SurveyResourceUpdateRequest = {
    title?: string;
    description?: string;
    is_public?: boolean;
    featured?: boolean;
    start_date?: string;
    end_date?: string | null;
    complete_message?: string;
    randomize?: boolean;
    enable_finding?: boolean;
    questions?: Array<SurveyResourceQuestionUpdate>;
};

export type ThreadCreateRequest = {
    owner_id: number;
    thumbnail?: string;
    title: string;
    url: string;
    kind: LearningResourceKind;
};

export type ThreadOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type ThreadResponse = {
    id: number;
    thumbnail: string;
    title: string;
    owner: ThreadOwner;
    url: string;
    kind: LearningResourceKind;
    comment_count: number;
    question_count: number;
    unsolved_count: number;
    created: string;
};

export type UserCreateRequest = {
    username: string;
    email: string;
    password: string;
    name: string;
    email_verification_url: string;
};

export type UserResponse = {
    id: number;
    username: string;
    email: string;
    name: string;
    thumbnail: string;
    description: string;
    created: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoDisplayResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: VideoOwner;
    thumbnail: string;
    uploader: string;
    duration: number | null;
    passing_percent: number;
    watch_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    progress: number | null;
    passed: boolean | null;
    modified: string;
    is_live: boolean;
    video_kind?: VideoKind | null;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type VideoKind = 'video' | 'short';

export type VideoOwner = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type VideoReportResponse = {
    user: VideoReportUser;
    first_watch: string | null;
    watched_at: string | null;
    progress: number | null;
    passed: boolean | null;
};

export type VideoReportUser = {
    id: number;
    username: string;
    name: string;
    thumbnail: string;
};

export type VideoResourceResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: VideoOwner;
    kind: LearningResourceKind;
    video_kind: VideoKind;
    passing_percent: number;
    uploader: string;
    thumbnail: (Blob | File) | string;
};

export type VideoSelectorResponse = {
    id: string;
    title: string;
    thumbnail: string;
};

export type VideoSubtitleResponse = {
    lang: string;
    lines: string;
};

export type VideoViewResponse = {
    id: string;
    title: string;
    description: string;
    is_public: boolean;
    featured: boolean;
    owner: VideoOwner;
    uploader: string;
    duration: number | null;
    passing_percent: number;
    watch_count: number;
    bookmark_count: number;
    like_count: number;
    flag_count: number;
    progress: number | null;
    passed: boolean | null;
    last_position: number | null;
    modified: string;
    video_kind: VideoKind;
    thumbnail: string;
    tag_names: Array<(string)>;
    is_live: boolean;
    bookmarked: boolean;
    liked: boolean;
    flagged: boolean;
};

export type WatchStartRequest = {
    first_watch: string;
};

export type WatchUpdateRequest = {
    watch_bitmap?: (Blob | File) | null;
    length?: number | null;
    last_position: number;
};

export type PublicCreateUserData = {
    requestBody: UserCreateRequest;
};

export type PublicCreateUserResponse = unknown;

export type PublicVerifyEmailData = {
    token: string;
};

export type PublicVerifyEmailResponse = unknown;

export type PublicResendVerificationEmailData = {
    requestBody: ResendVerificationEmailRequest;
};

export type PublicResendVerificationEmailResponse = unknown;

export type PublicLoginData = {
    formData: Body_PublicLogin;
};

export type PublicLoginResponse = unknown;

export type AccountLogoutData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type AccountLogoutResponse = unknown;

export type PublicPasswordResetData = {
    requestBody: PasswordResetRequest;
};

export type PublicPasswordResetResponse = unknown;

export type PublicPasswordResetConfirmData = {
    requestBody: PasswordResetConfirmRequest;
};

export type PublicPasswordResetConfirmResponse = unknown;

export type AccountGetMeData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type AccountGetMeResponse = UserResponse;

export type AccountUpdateMeData = {
    accessToken?: string | null;
    formData?: Body_AccountUpdateMe;
    refreshToken?: string | null;
};

export type AccountUpdateMeResponse = UserResponse;

export type AccountGetUserData = {
    accessToken?: string | null;
    id: number;
    refreshToken?: string | null;
};

export type AccountGetUserResponse = UserResponse;

export type AccountGetUserByUsernameData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    username: string;
};

export type AccountGetUserByUsernameResponse = UserResponse;

export type CommentGetThreadData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    url: string;
};

export type CommentGetThreadResponse = ThreadResponse;

export type CommentGetThreadsData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'comment_count' | 'question_count' | 'unsolved_count';
    ownerId?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type CommentGetThreadsResponse = Paginated_ThreadResponse_;

export type CommentCreateThreadData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ThreadCreateRequest;
};

export type CommentCreateThreadResponse = ThreadResponse;

export type CommentGetDisplaysData = {
    accessToken?: string | null;
    orderBy?: 'created' | 'like_count';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    threadId?: number | null;
};

export type CommentGetDisplaysResponse = Paginated_CommentDisplayResponse_;

export type CommentCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: CommentResourceCreateRequest;
};

export type CommentCreateResourceResponse = CommentResourceResponse;

export type CommentUpdateResourceData = {
    accessToken?: string | null;
    id: number;
    refreshToken?: string | null;
    requestBody: CommentUpdateRequest;
};

export type CommentUpdateResourceResponse = CommentResourceResponse;

export type CommentToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: number;
    refreshToken?: string | null;
};

export type CommentToggleActionResponse = unknown;

export type VideoGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'watched_at' | 'title' | 'modified';
    owner?: number | null;
    page?: number;
    playlistId?: string | null;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    tag?: string | null;
    videoKind?: VideoKind | null;
};

export type VideoGetDisplaysResponse = Paginated_VideoDisplayResponse_;

export type VideoImportYoutubeVideoData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ImportYoutubeRequest;
};

export type VideoImportYoutubeVideoResponse = VideoDisplayResponse;

export type VideoGetViewData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoGetViewResponse = VideoViewResponse;

export type VideoGetSubtitlesData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoGetSubtitlesResponse = Array<VideoSubtitleResponse>;

export type VideoGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoGetResourceResponse = VideoResourceResponse;

export type VideoUpdateResourceData = {
    accessToken?: string | null;
    formData?: Body_VideoUpdateResource;
    id: string;
    refreshToken?: string | null;
};

export type VideoUpdateResourceResponse = VideoResourceResponse;

export type VideoDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoDeleteResourceResponse = unknown;

export type VideoGetWatchBitmapData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoGetWatchBitmapResponse = (Blob | File);

export type VideoStartWatchData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: WatchStartRequest;
};

export type VideoStartWatchResponse = unknown;

export type VideoUpdateWatchData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: WatchUpdateRequest;
};

export type VideoUpdateWatchResponse = unknown;

export type VideoEndWatchData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type VideoEndWatchResponse = unknown;

export type VideoGetVideoReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'first_watch' | 'last_watch';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type VideoGetVideoReportResponse = Paginated_VideoReportResponse_;

export type VideoDownloadVideoReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'first_watch' | 'last_watch';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type VideoDownloadVideoReportResponse = string;

export type VideoToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type VideoToggleActionResponse = unknown;

export type VideoVideoSelectorData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type VideoVideoSelectorResponse = Array<VideoSelectorResponse>;

export type PlaylistGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'title' | 'modified';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type PlaylistGetDisplaysResponse = Paginated_PlaylistDisplayResponse_;

export type PlaylistImportYoutubePlaylistData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ImportYoutubeRequest;
};

export type PlaylistImportYoutubePlaylistResponse = PlaylistDisplayResponse;

export type PlaylistUpdatePlaylistVideosData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: PlaylistVideoRequest;
};

export type PlaylistUpdatePlaylistVideosResponse = unknown;

export type PlaylistGetViewData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type PlaylistGetViewResponse = PlaylistViewResponse;

export type PlaylistResumePlaylistData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type PlaylistResumePlaylistResponse = PlaylistResumeResponse;

export type PlaylistGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type PlaylistGetResourceResponse = PlaylistResourceResponse;

export type PlaylistUpdateResourceData = {
    accessToken?: string | null;
    formData?: Body_PlaylistUpdateResource;
    id: string;
    refreshToken?: string | null;
};

export type PlaylistUpdateResourceResponse = PlaylistResourceResponse;

export type PlaylistDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type PlaylistDeleteResourceResponse = unknown;

export type PlaylistCreateResourceData = {
    accessToken?: string | null;
    formData: Body_PlaylistCreateResource;
    refreshToken?: string | null;
};

export type PlaylistCreateResourceResponse = PlaylistResourceResponse;

export type PlaylistToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type PlaylistToggleActionResponse = unknown;

export type QuizGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type QuizGetDisplaysResponse = Paginated_QuizDisplayResponse_;

export type QuizGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizGetResourceResponse = QuizResourceResponse;

export type QuizUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: QuizResourceUpdateRequest;
};

export type QuizUpdateResourceResponse = QuizResourceResponse;

export type QuizDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizDeleteResourceResponse = unknown;

export type QuizCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: QuizResourceCreateRequest;
};

export type QuizCreateResourceResponse = QuizResourceResponse;

export type QuizGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizGetAssessResponse = QuizAssessResponse;

export type QuizReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizReadyAssessResponse = QuizAssessResponse;

export type QuizSubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: QuizAssessSubmitRequest;
};

export type QuizSubmitAssessResponse = QuizAssessResponse;

export type QuizDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type QuizDeleteAssessResponse = unknown;

export type QuizGetQuizReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type QuizGetQuizReportResponse = Paginated_QuizReportResponse_;

export type QuizDownloadQuizReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type QuizDownloadQuizReportResponse = string;

export type QuizToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type QuizToggleActionResponse = unknown;

export type QuizGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type QuizGetOwnedQuestionsResponse = Array<QuizResourceQuestionResource>;

export type SurveyGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type SurveyGetDisplaysResponse = Paginated_SurveyDisplayResponse_;

export type SurveyGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyGetResourceResponse = SurveyResourceResponse;

export type SurveyUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: SurveyResourceUpdateRequest;
};

export type SurveyUpdateResourceResponse = SurveyResourceResponse;

export type SurveyDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyDeleteResourceResponse = unknown;

export type SurveyCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: SurveyResourceCreateRequest;
};

export type SurveyCreateResourceResponse = SurveyResourceResponse;

export type SurveyGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyGetAssessResponse = SurveyAssessResponse;

export type SurveyReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyReadyAssessResponse = SurveyAssessResponse;

export type SurveySubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: SurveyAssessSubmitRequest;
};

export type SurveySubmitAssessResponse = SurveyAssessResponse;

export type SurveyDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type SurveyDeleteAssessResponse = unknown;

export type SurveyGetSurveyReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type SurveyGetSurveyReportResponse = Paginated_SurveyReportResponse_;

export type SurveyDownloadSurveyReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type SurveyDownloadSurveyReportResponse = string;

export type SurveyToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type SurveyToggleActionResponse = unknown;

export type SurveyGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type SurveyGetOwnedQuestionsResponse = Array<SurveyResourceQuestionResource>;

export type ExamGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'created' | 'submission_count';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type ExamGetDisplaysResponse = Paginated_ExamDisplayResponse_;

export type ExamGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamGetResourceResponse = ExamResourceResponse;

export type ExamUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamResourceUpdateRequest;
};

export type ExamUpdateResourceResponse = ExamResourceResponse;

export type ExamDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamDeleteResourceResponse = unknown;

export type ExamCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: ExamResourceCreateRequest;
};

export type ExamCreateResourceResponse = ExamResourceResponse;

export type ExamGetAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamGetAssessResponse = ExamAssessResponse;

export type ExamReadyAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessReadyRequest;
};

export type ExamReadyAssessResponse = ExamAssessResponse;

export type ExamStartAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessStartRequest;
};

export type ExamStartAssessResponse = ExamAssessResponse;

export type ExamSubmitAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamAssessSubmitRequest;
};

export type ExamSubmitAssessResponse = ExamAssessResponse;

export type ExamDeleteAssessData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ExamDeleteAssessResponse = unknown;

export type ExamGetGradingData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    userId: number;
};

export type ExamGetGradingResponse = ExamAssessResponse;

export type ExamSubmitGradingData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ExamGradingRequest;
    userId: number;
};

export type ExamSubmitGradingResponse = ExamAssessResponse;

export type ExamGetExamReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time' | 'start_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
    upTo?: string | null;
};

export type ExamGetExamReportResponse = Paginated_ExamReportResponse_;

export type ExamDownloadExamReportData = {
    accessToken?: string | null;
    asOf?: string | null;
    id: string;
    orderBy?: 'end_time' | 'start_time';
    refreshToken?: string | null;
    search?: string | null;
    upTo?: string | null;
};

export type ExamDownloadExamReportResponse = string;

export type ExamGetGradingSubmissionsData = {
    accessToken?: string | null;
    orderBy?: 'end_time' | 'start_time';
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type ExamGetGradingSubmissionsResponse = Paginated_ExamGradingSubmissionReponse_;

export type ExamToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type ExamToggleActionResponse = unknown;

export type ExamGetOwnedQuestionsData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type ExamGetOwnedQuestionsResponse = Array<ExamResourceQuestionResource>;

export type LessonGetDisplaysData = {
    accessToken?: string | null;
    bookmarker?: number | null;
    orderBy?: 'title' | 'modified';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type LessonGetDisplaysResponse = Paginated_LessonDisplayResponse_;

export type LessonGetViewData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type LessonGetViewResponse = LessonViewResponse;

export type LessonGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type LessonGetResourceResponse = LessonResourceResponse;

export type LessonUpdateResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: LessonResourceUpdateRequest;
};

export type LessonUpdateResourceResponse = LessonResourceResponse;

export type LessonDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type LessonDeleteResourceResponse = unknown;

export type LessonCreateResourceData = {
    accessToken?: string | null;
    refreshToken?: string | null;
    requestBody: LessonResourceCreateRequest;
};

export type LessonCreateResourceResponse = LessonResourceResponse;

export type LessonToggleActionData = {
    accessToken?: string | null;
    action: 'bookmark' | 'like' | 'flag';
    id: string;
    refreshToken?: string | null;
};

export type LessonToggleActionResponse = unknown;

export type LessonResourceSelectorData = {
    accessToken?: string | null;
    refreshToken?: string | null;
};

export type LessonResourceSelectorResponse2 = Array<LessonResourceSelectorResponse>;

export type ContentGetDisplaysData = {
    accessToken?: string | null;
    orderBy?: 'title' | 'modified';
    owner?: number | null;
    page?: number;
    refreshToken?: string | null;
    search?: string | null;
    size?: number;
};

export type ContentGetDisplaysResponse = Paginated_ContentDisplayResponse_;

export type ContentGetViewData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ContentGetViewResponse = ContentViewResponse;

export type ContentGetResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ContentGetResourceResponse = ContentResourceResponse;

export type ContentUpdateResourceData = {
    accessToken?: string | null;
    formData?: Body_ContentUpdateResource;
    id: string;
    refreshToken?: string | null;
};

export type ContentUpdateResourceResponse = ContentResourceResponse;

export type ContentDeleteResourceData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ContentDeleteResourceResponse = unknown;

export type ContentCreateResourceData = {
    accessToken?: string | null;
    formData: Body_ContentCreateResource;
    refreshToken?: string | null;
};

export type ContentCreateResourceResponse = ContentResourceResponse;

export type ContentUpdateResource2Data = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
    requestBody: ContentResourceUpdateRequest;
};

export type ContentUpdateResource2Response = ContentResourceResponse;

export type ContentPresignedUploadUrlData = {
    accessToken?: string | null;
    contentId: string;
    contentType: string;
    filename: string;
    refreshToken?: string | null;
};

export type ContentPresignedUploadUrlResponse = string;

export type ContentContentIframeData = {
    accessToken?: string | null;
    id: string;
    refreshToken?: string | null;
};

export type ContentContentIframeResponse = string;

export type SearchSuggestVideoKeywordsData = {
    accessToken?: string | null;
    q?: string;
    refreshToken?: string | null;
};

export type SearchSuggestVideoKeywordsResponse = Array<(string)>;